routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('tasks', 'TaskController')->middleware('auth');
Route::resource('topics', 'TopicController')->middleware('auth');
Route::resource('meets', 'MeetController')->middleware('auth');
Route::resource('usercodes', 'UsercodeController')->middleware('auth');

Route::resource('users', 'UserController')->middleware('auth');
Route::resource('usermeets', 'UsermeetController')->middleware('auth');
Route::resource('organizations', 'OrganizationController')->middleware('auth');
Route::get('tasks/done1/{id}', 'MeetController@statusmeet')->name('done1');
Route::get('tasks/iscom/{id}', 'MeetController@iscom1')->name('iscom');
Route::get('tasks/trying/{id}', 'MeetController@status')->name('trying');
Route::get('tasks/done/{id}', 'TaskController@done')->name('done');
Route::get('meets/create1/{id}', 'MeetController@create1')->name('create1');
Route::get('users/change', 'UserController@change')->name('change');
Route::get('tasks/create/{meet_id?}', 'TaskController@create');
Route::get('topics/create/{meet_id?}', 'TopicController@create');
Route::get('topics/edit/{meet_id?}', 'TopicController@edit');
Route::get('/sendemail', 'SendEmailController@index');
Route::post('/sendemail/send', 'SendEmailController@send');
Route::get('topics/done/{id}', 'TopicController@done')->name('donetopic');
Route::get('usermeets/create/{meet_id?}', 'UsermeetController@create');
Route::get('/allmeets', 'MeetController@allmeets');

Route::get('/dashboard', 'UserController@dashboard')->name('dashboard');
Route::get('users/code/{id}', 'UserController@code')->name('code');
Route::get('chart', 'ChartController@index');
Route::resource('deshbords', 'DeshbordController')->middleware('auth');

app/Topic.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Topic extends Model
{
    protected $fillable = [
        'name', 'meet_id','namemeet','iscomplete'
    ];
    public function meets()
    {
        return $this->belongsTo('App\Meet');
    }
}

app/Http/Controllers/TopicController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Meet;
use App\User;
use App\Task;
use App\Topic;
use App\Usermeet;
use App\Organization;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Gate::denies('manager')){  
            if (Gate::denies('invitor')) {
                if (Gate::denies('participant')) {
                abort(403,"Are you a hacker or what?");} }}  
        $id=Auth::id();
       if (Gate::allows('invitor')) {
            $meets=  DB::table('meets')->where('user_id', $id)->value('id');
            $topics=  Topic::where('meet_id' , $meets)->get();
           return view('topics.index', compact('topics'));
        }
     $meeting = DB::table('usermeets')->where('user_id', $id)->value('meet_id');
     $topics = Topic::where('meet_id' , $meeting)->get();
        return view('topics.index', compact('topics'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create( $meet_id=null )
    {
        $meets=null;
        if(!$meet_id){
            $meets = Meet::where('user_id' , Auth::user()->id)->get();
        }
        return view('topics.create',['meet_id'=>$meet_id,'meets'=>$meets]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $topic = new Topic();
        $id =Auth::id();
        
        
        $topic->name = $request->name;
       $topic->meet_id=$request->meet_id;
        
        $boss = DB::table('meets')->where('id',$request->meet_id)->first();
       $topic->namemeet=$boss->title;
       $user =  DB::table('users')->where('id',$id)->first();
       $bossorg = DB::table('organizations')->where('id',$user->code)->first();
       $try = $bossorg->min_item;
       $topic->save();
       $organization=Organization::all();
      
        $votes = Topic::where('meet_id',$request->meet_id)->count();
        
        
        if ($votes<$try){
        return redirect('topics/create');}
        return redirect('usermeets/create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $topic = Topic::find($id);
        $meets = Meet::where('user_id' , Auth::user()->id)->get();
        
        return view('topics.edit',['topic' => $topic,'meets'=>$meets]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $topic = Topic::find($id);
        $topic->update($request->all()); 
        return redirect('topics');
    }
    public function done($id)
    {
        //only if this todo belongs to user 
                 
        $topic = Topic::findOrFail($id);  
        $boss = DB::table('meets')->where('id',$topic->meet_id)->first();        
        $todayDate = date("Y-m-d");
        $todayTime = date("H:i:s");
        if (($todayDate< $boss->start_date)|| ($todayTime< $boss->start_time) ||  ($todayTime> $boss->end_time) ) {
            abort(403,"sorry you can edit only the meeting ");
        }  
        $topic->iscomplete = 1; 
        $topic->save();
        return redirect('topics');    
    }    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $topic = Topic::find($id);
        $topic->delete();
        return redirect('topics');

    }


}

resources/views/topics/create.blade.php
@extends('layouts.app')
@section('content')

<h1>Create a new topic</h1>
<form method = 'post' action = "{{action('TopicController@store')}}" >

{{csrf_field()}}      

<div class = "form-group">
<br>
<div class="col-md-4">
    <label class="control-label" for = "name"> topic name </label>
    </div>
    <div class="col-md-10">
    <input type = "text" class = "form-control" name = "name" required>
    </div>
    <br>
  
    @if($meets != null)
    <div class="col-md-4">
    <label class="control-label" for = "name"> Meet Name </label>
    </div>

    <div class="col-md-10">
    <select class="form-control" name = "meet_id">
    @foreach($meets as $meet)
  
  <option value="{{$meet->id}}"> {{$meet->title}}</option>
  @endforeach  

  
</select></div>@endif






    <br>

    <div class = "form-group">    
    <input type = "submit" class = "submit-button" name = "submit" value = "Save">

</div>
</div>

</form>

@endsection


<style>
.submit-button{
  background-color: #555555; 
  border: none;
  color: white;
  padding: 8px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 20px 18px;
  cursor: pointer;
  height: 40px;
}

.form-group{
background: #E6E6FA;
width:50%;
border-radius: 3%;
padding: 2%;
}
</style>

resources/views/topics/edit.blade.php
@extends('layouts.sidebar')
@section('content')

<h1>Edit topic</h1>
<form method = 'post' action = "{{action('TopicController@update', $topic->id)}}" >
@csrf      
@method('PATCH')    

<div class = "form-group">

<div class="col-md-4">  
<label class="control-label" for = "name"> topic to Update </label>
    </div>
    <div class="col-md-10">
    <input type = "text" class = "form-control" name = "name" value ="{{$topic->name}}">
</div>

@if($meets != null)
    <div class="col-md-4">
    <label class="control-label" for = "name"> Meet Name </label>
    </div>

    <div class="col-md-10">
    <select class="form-control" name = "meet_id">
    @foreach($meets as $meet)
  
  <option value="{{$meet->id}}"> {{$meet->title}}</option>
  @endforeach 
  </select></div>@endif
<br>
  <div class="col-md-2">    
    <input type = "submit" class = "submit-button" name = "submit" value = "Update">
</div>
</div>
</form>



@endsection

<style>
.submit-button{
  background-color: #555555; 
  border: none;
  color: white;
  padding: 8px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 20px 18px;
  cursor: pointer;
  height: 40px;
}

.form-group{
background: #E6E6FA;
width:50%;
border-radius: 3%;
padding: 2%;

}

</style>

resources/views/topics/index.blade.php
@extends('layouts.sidebar')
@section('content')
                
           
<div class="panel panel-default panel-table">
     <div class="row">
             <div class="col col-xs-6" style="font-family: Arial Black, Gadget, sans-serif;">
                <h3>Topics</h3>
             </div>
               
                    
                    <!-- <li><a href="{{route('meets.index')}}" class="btn btn-success">@lang('Back to meets')</a></li> -->
                    
              
 <div class="col col-xs-6 text-right " style="margin-top: 5%;">  
 @cannot('participant')<a href="{{ route('topics.create') }}"
     class="btn btn-sm btn-primary btn-create" >@lang('add a new topic')</a> 
 </div>@endcannot
                </div>
                </div>
            


<div class="table-responsive">
        <table class="table table-bordered">
<thead>
<tr>
<th  style=" text-align: center;"> Name</th>

<th  style=" text-align: center;"> Name_Meet</th>

</tr> 
</thead>
<tbody>
<tr>
@foreach($topics as $topic)

<td align="center" style="vertical-align: middle;" > {{$topic->name}}</td> 
<td align="center" style="vertical-align: middle;"> {{$topic->namemeet}} </td>
@cannot('participant')<td align="center" style="vertical-align: middle;">
<a href="{{route('topics.edit', $topic->id)}}" class="btn btn-success">@lang('Edit')</a>
</td>
<td align="center" style="vertical-align: middle;margin-block-end: 0em;">
<form style="margin-block-end: 0em;" method = 'post' action = "{{action('TopicController@destroy',$topic->id)}}" >
@csrf   
@method('DELETE')   
<div>    

<button type="submit" class="btn btn-danger">@lang('delete')</button>
</div>
</td>@endcannot

</form>

</tr>

@endforeach  
</tbody>
</table>
</div>  
</div>           
            </div>
            


@endsection

<style>
.table-responsive{
    /* padding-top:50px; */
  

}



</style>